### ISSUE TITLE
:chart: Display more data fields

### ISSUE THREAD

**Issue by mfisher87** [proj-forge/proj-forge.github.io#3]
Several data fields are commented out in the [CRS Jinja template](https://github.com/proj-forge/proj-forge.github.io/blob/main/src/projections_site/templates/crs.html.j2). Make those work. The comments are based on utility functions by @andypbarrett (https://github.com/andypbarrett/epsg-site-demo/blob/main/util.py). If we re-use any of that code, be sure to reach out to Andy and ask for the code to be licensed, and be sure to credit his work!

Look at other sites and see what important information they're displaying that we're not, and display more stuff :)

**Comment by sunny-bak** [comment]
for geodetic_crs, I used crs.name just to get the name from the crs. would that be sufficient? if so, you can close the issue. 
thanks!

**Comment by mfisher87** [comment]
The way @andypbarrett calculated that value in his prototype was: `crs.source_crs.to_json_dict()["name"]`. What do you think?
